set dotenv-load := true

# Project and region configuration
gcp_project := "neurons-ml"
gcp_region := "us-central1"

# Docker image configuration
revision := `git rev-parse --short HEAD`
local_image_name := "object_detection_gradio"
local_image := local_image_name + ":" + revision
remote_image_name := gcp_region + "-docker.pkg.dev" / gcp_project / "vertex/object_detection"
remote_image := remote_image_name + ":" + revision

# Service account email
service_account := "vertex-ai@neurons-ml.iam.gserviceaccount.com"

# Deployment paths
deploy_dir := ".deploy"
deploy_env_vars_template := deploy_dir / "env_vars.yaml.template"
deploy_env_vars_file := deploy_dir / "env_vars.yaml"

# Default task: list all tasks
[private]
default:
  @just --list

# Run the app locally
run *args:
  python main.py {{ args }}

# Build Docker image
[confirm]
[doc("Build Docker image")]
build:
  gcloud auth configure-docker '{{ gcp_region }}-docker.pkg.dev'
  docker build --platform 'linux/amd64' --tag '{{ local_image }}' .

# Push Docker image to Artifact Registry
[confirm]
[doc("Push Docker image to Artifact Registry")]
push: build
  docker image tag '{{ local_image }}' '{{ remote_image }}'
  docker image push '{{ remote_image }}'

# Deploy to Cloud Run with a service account
[confirm]
[doc("Deploy the current working tree to Cloud Run")]
deploy: make-env-vars-file push
  gcloud run deploy object-detection-gradio \
    --project='{{ gcp_project }}' \
    --region='{{ gcp_region }}' \
    --image='{{ remote_image }}' \
    --env-vars-file='{{ deploy_env_vars_file }}' \
    --allow-unauthenticated \
    --service-account='{{ service_account }}'

# Create the environment variable file used for deployment
[private]
[doc("Create the environment variable file used for deployment")]
make-env-vars-file:
  envsubst < '{{ deploy_env_vars_template }}' > {{ deploy_env_vars_file }}

# Clean Docker artifacts and cache
[confirm]
[doc("Clean up Docker cache and images")]
clean:
  docker system prune -f
